apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "app-{{ .JobName }}"
  name: "deploy-{{ .JobName }}"
  namespace: "{{ .ApplicationNamespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app-{{ .JobName }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "app-{{ .JobName }}"
    spec:
      containers:
      - image: "{{ .ImageDestination }}"
        imagePullPolicy: Always
        name: "c-{{ .JobName }}"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: "app-{{ .JobName }}"
#   name: "svc-{{ .JobName }}"
# spec:
#   ports:
#   - port: 1234
#     protocol: TCP
#   selector:
#     app: "app-{{ .JobName }}"